python/docsbuild-scripts

build_docs.py
First we need to update the salt rules to have the initial checkout done from the git repo in the server.
Please do not merge unless said explicitly,
=> WIP: Pull using git command for the repo

build_docs.py
=> Update for 3.7 build, amend purging slightly

build_docs.py
see: https://github.com/python/docsbuild-scripts/issues/16
I first though missing translations (typiaclly 3.7) should fail more cleanly than an exception logged with full stacktrace, probably something like "INFO: No translation for branch 3.7 in lang fr". But doing so I though we should probably just build them with the nearest translation, like 3.6, as lots of string are in common.
Tested locally with:
python3 ./build_docs.py --git --build-root /tmp/build_root/ --www-root /srv/docs.python.org --log-directory /tmp/log_root/ --skip-cache --quick
=> FIX issue 16: Build missing translations branches with nearest one.

build_docs.py
This commit permit to use the new venv (https://github.com/python/psf-salt/pull/111) so we have Python 3.6 so blurb can work (https://github.com/python/docsbuild-scripts/issues/14).
=> issue 14: Use new venv, with Python 3.6 and blurb.

build_docs.py
fixes https://github.com/python/docsbuild-scripts/issues/27
=> Deprecate the --git flag (use git by default).

build_docs.py
see https://github.com/python/docsbuild-scripts/issues/37
=> Stop building the devguide, it's on RTD now.

requirements.txt
Context: https://github.com/python/cpython/pull/2017#issuecomment-364622147
=> Pull common docs theme from PyPI

build_docs.py
https://mail.python.org/pipermail/doc-sig/2018-January/003996.html
=> Adding python-docs-ko.

build_docs.py
see https://github.com/python/docsbuild-scripts/issues/21
=> More robust subprocess invocation.

build_docs.py
Both teams have the first commit in their repo. So let's start to
build them.
cc @adrianliaw for zh-tw translation.
=> Add zh-{cn,tw} to build_docs

build_docs.py, requirements.txt
Having sphinx 2 in prod will allow us not to fail during the txt build of master, allowing to build pdf and epub.
I have to test it locally before merging.
=> Bump requirements.

build_docs.py
Add "id" (Indonesian Translation) to Documentation build scripts.
=> Add "id" to build_docs.py

requirements.in, requirements.txt
https://github.com/sphinx-doc/sphinx/blob/2a0e560/sphinx/search/zh.py#L19
Chinese stemmer is implemented with library `jieba`.
=> Support Chinese search in Sphinx

build_docs.py
Like in https://sentry.io/organizations/python-software-foundation/issues/1562420861/?project=1307574&referrer=alert_email
=> FIX: git reset --hard in case someone force pushed and fast-forward is not possible.

build_docs.py
Trying a local build before merging, it'll take time.
=> Pin sphinx

build_docs.py
This avoid the following commands to fail too. This way the root cause
is easier to spot, as it's the only error being logged.
=> Stop a build on the first failing command.

templates/switchers.js
In order to help accessibility, I just added some id to the select tags.
=> switchers select tags should have a correct id

build_docs.py
It has been updated in Docs/requirements.txt of CPython at 31 of October 2021.
https://github.com/python/cpython/commit/14a4fce457033412278ca9a056787db424310dc3
=> Update Sphinx version for main branch (3.11)

build_docs.py
=> Update build_docs.py Adding italian language

build_docs.py
In preparation of the 3.12.0 release later today
A
=> Latest and greatest (3.12.0)

templates/robots.txt
These were initially added in #99, and removed in c49181f (six months ago) -- it might be worth adding them back?
cc: @JulienPalard
A
=> Add EOL versions back to the sitemap

templates/404.html
re @encukou's https://github.com/python/docsbuild-scripts/issues/163#issuecomment-1747480861
A
=> Add a link to the download archives

build_docs.py
It was mandatory for the server to queue builds, but since 1a0ad2e it's no longer needed.
Queuing builds has a downside: if the daily builds take more than 24h they starts to infinitly queue.
=> Don't queue builds.

build_docs.py
https://github.com/python/cpython/issues/122868#issuecomment-2278777836
A
=> Use ``--upgrade-strategy=eager`` for pip

build_docs.py
=> Fix `--theme` help message typo.

build_docs.py
Fixes https://github.com/python/docsbuild-scripts/issues/190.
=> Build each docs version with fresh commit

build_docs.py
=> Log the output of the sphinx ``make`` command

check_times.py
This updates ``check_times.py`` to use the new `state.toml` information that we've been logging for a few days.
A
=> Use saved state information in ``check_times.py``

check_times.py
=> Include full build duration

build_docs.py
Alternative to https://github.com/python/cpython/pull/125264.
A
=> Use PyStemmer

build_docs.py
=> Further simplify symlink removal

templates/switchers.js
Per https://github.com/python/docsbuild-scripts/pull/225#issuecomment-2448192443
cc @hugovk 
A
=> Keep switcher placeholder classes

build_docs.py
Required by https://github.com/python/cpython/pull/132101
=> Define ``ogp_site_url`` for social media cards

build_docs.py
Currently we rebuild & purge all symlinks every time any version is changed. This is wasteful. This PR alters symlink recreation/purging to only occur when the relevant target version and language has changed.
=> Only recreate a symlink when the relevant target is rebuilt

build_docs.py
Previously, identical content for ``switchers.js`` was rendered for each version-language pair. This commit pre-renders the content of the file, then writing it to disk for each version-language pair.
=> Extract ``switchers.js`` rendering into a new function.

build_docs.py
Canonical links will not change if no versions were built, which is a common case for the `only-html-en` builder. This saves about two minutes on each build if no work needs to be done.
A
=> Skip checking canonical links if nothing was built
