build_docs.py
This patch will help me provide a cleaner patch to build french (and other translations) documentation. It's also a lot easier for me to test it now that I can change the used paths.
`build_one` was taking paths of checkout and destination and was
compiling them without knowing which version it was. As I'd like in a
near future also build translated documentations, I'd need to know
which version is being compiled. As it's possible, from the version
number to build the paths that was given, I think it's a good idea to
pass the version number instead of the various paths.
As I needed to allow the version to be given, and as I wanted to test
it in my home directory, I used argparse to hold the default values
for the various paths still allowing me to give paths to /tmp/ or my
home directory. …
=> Slowly prepare for french translations.

build_docs.py
I implemented some new flags to allow the script to be executed anywhere, which is necessary for me to test it locally:
- `--log-directory`: To log outside of /var/logs/ when testing locally
- `--group`: To chgrp to someone else than "docs" when testing locally
- `--git`: To use git instead of mercurial
- `--skip-cache-invalidation: To avoid calling PURGE on fastly (which are probably just ignored).
Obviously the new options have production-ready default values, so it's again a drop-in replacement: no salt modification needed.
I also resolved the TODO about implementing fastly cache invalidation on the devguide.
CC @ewdurbin
=> Testability / portability (and fastly invalidation on devguide)

requirements.txt
Commiting fix for https://github.com/python/docsbuild-scripts/issues/14 as it just hit me while testing something else... (I didn't checked why blurb is needed but I got a build error telling blurb is missing). I'm now building locally with blurb==1.0.4, so far it's working.
=> issue 14: blurb is now a requirement.

build_docs.py
I see something like:
drwxr-xr-x 19 docsbuild docs      4.0K Jul 10 04:26 3.5
drwxr-xr-x 19 docsbuild docs      4.0K Jul 10 05:05 3.6
drwxrwx--- 19 docsbuild docsbuild 4.0K Aug  1 23:19 3.7
With the chmod of https://github.com/python/docsbuild-scripts/pull/19
and this chgrp everything should be fixed.
=> issue 18: run a chgrp to fix group of directories.

build_docs.py
As the current ulimit is 0007, directories created with mode=0o775 were created with mode 770, disallowing nginx and human users to traverse them.
=> issue 18: Explicitly use chmod to set directory modes

requirements.txt
Additionally update all existing dependencies in requirements.txt, as the common theme requires sphinx >= 1.6.0.
Context:
* https://github.com/python/cpython/pull/2017
* https://bugs.python.org/issue30607
=> Add common docs theme as a dependency

build_docs.py
I'm having hard times to read the actual logs (see where it start and stop), and spotting translations errors in `/var/log/docsbuild/python37.log` is hard as english and translations are mixed here. So I'd prefer using separate files for each languages, and being more explicit on which language is currently worked on.
=> Split sphinx log files by translations.

build_docs.py
Current script is purging directories without trailing slash, like: "docs.python.org/3.6" which is never hit, users hit docs.python.org/3.6/, so we're adding the missing `/` during invalidation to properly invalidate this.
Fixes https://github.com/python/docsbuild-scripts/issues/23
=> FIX issue 23: Add missing trailing slash during cache invalidation

build_docs.py
Fixing https://github.com/python/docsbuild-scripts/issues/10
I kept the cp -a for the archives as it may be expected to have some archives in the archives/ directory.
=> Change cp -a to rsync -a --delete-delay to remove old, unused files.

build_docs.py
Explicit is better than implicit.
=> build-docs needs paths to blurb and venv

requirements.txt
The issue https://bugs.python.org/issue31737 looks fixed in sphinx 1.6.3, and sphinx 1.6.4 has also been released, so maybe time to upgrade,
I tried a local build, https://bugs.python.org/issue31589 is not fixed, but everything else went well.
=> bpo-31737: Bump sphinx version.

README.txt, build_docs.py
This tries to fix https://bugs.python.org/issue31584 and can't hurt,
anyway the cron could have started (or would have ended up getting
started, after adding some languages) before the previous run was
complete.
=> Use different cpython clones to build different languages.

build_docs.py
dirname for .../fr/3.6/ was giving .../fr/, the rest was constructed
from here, purging without the /fr/. Building from the webroot make
more sense semantically than "the parent folder", and it fixees the
issue.
=> FIX: Cache invalidation problem for translations.

build_docs.py
This contains two parts, first the switch between xelatex (for french and english) and platex (for japanese). This switch is hard to put in cpython Doc/conf.py for the moment as we don't know the language while the conf is executed.
The other part is the drop of latex_elements, which can be backported to cpython with a xelatex engine, as it works well to generate english PDF.
Oh I also added a -j4 to sphinx build.
=> [WIP] Configuration to properly build PDFs in japanese and french 

build_docs.py, requirements.txt
From 45mn to 5mn for a full build on my machine with -j 16.
=> Add --jobs to allow for some parallelism.

build_docs.py
This is to avoid issues like find seeing rsync's temporary files, raising errors like:
find: `/srv/docs.python.org/zh-tw/3.6/library/.bz2.html.e2Dgob': No such file or directory
Oh, I passed black (in a separate commit), hope it's OK as I'm more or less alone here, I hope to get pylint and flake8 to pass too, maybe a bit of travis after that. But don't hesitate to tell me if you don't want to.
=> Avoid parallel rsync and find

build_docs.py
I expect this to be fixed in newer toolchains, but as we almost never
use the output of those commands (except for logging purposes), it's
safe to use a backslashreplace.
=> Sometimes, the latex toolchain prints non-UTF8 sequences, like a 0xa7 alone

build_docs.py
Currently the Chinese pdf is broken. Take tutorial.pdf for example,
All Chinese characters are missing.
xeCJK should work, at least on my desktop, Debian testing. But I'm not sure if it works on the server.
[xeCJK](https://ctan.org/pkg/xecjk) is in texlive-xetex package, and it will use the [Fandol font](https://ctan.org/pkg/fandol), which should be in texlive-lang-chinese package.
=> Use xeCJK when building Chinese pdf

build_docs.py
The last commit was only tested with the latex make target, with:
`make SPHINXOPTS="-D latex_elements.fontenc='\usepackage{xeCJK}'" latex`.
It works without escaping backslash(only needs single quotas),
and we only need escape it in python code.
However the build_docs script is using autobuild-* make target.
In autobuild-dev target,
```
autobuild-dev:
make dist SPHINXOPTS='$(SPHINXOPTS) -Ea -A daily=1 -A switchers=1'
```
it calls another make target and manipulates the SPHINXOPTS environment,
so the origin single quotas no longer works.
we should call:
`make SPHINXOPTS='-D latex_elements.fontenc=\\usepackage{xeCJK}' autobuild-dev`
And in python code, we need two raw backslash.
=> Fix backslash escape in SPHINXOPTS

build_docs.py
This is because currently all CalledProcessError are grouped under the same group in sentry, so `CalledProcessError Command '['chgrp', '-R', 'docs', '/srv/docs.python.org/3.7']' returned non-zero exit status 1.` can contain a `CalledProcessError Command '['make', '-C `... which is not helpful.
=> Sentry: Split CalledProcessError in a distinct group by program.

requirements.txt
See https://bugs.python.org/issue39514 for more details.
=> bpo-39514: Bump python-docs-theme to 2020.1

README.md, build_docs.py, requirements.in, requirements.txt
Blocked by https://github.com/python/psf-salt/pull/193
=> Use a specific venv for specific sphinx versions.

build_docs.py
The Spanish translation of the documentation reached all the required translated files to be shown in the language selector under docs.python.org.
@JulienPalard Please, let me know if there is something else needed here. Thanks for all your help!
=> Show Spanish translation in production

build_docs.py, requirements.in, templates/robots.txt, templates/sitemap.xml
It looks like this:
```xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
xmlns:xhtml="http://www.w3.org/1999/xhtml">
<url>
<loc>https://docs.python.org/3.5/</loc>
<xhtml:link rel="alternate" hreflang="zh-CN" href="https://docs.python.org/zh-cn/3.5/"/>
<xhtml:link rel="alternate" hreflang="en" href="https://docs.python.org/en/3.5/"/>
<xhtml:link rel="alternate" hreflang="fr" href="https://docs.python.org/fr/3.5/"/>
<xhtml:link rel="alternate" hreflang="es" href="https://docs.python.org/es/3.5/"/>
<xhtml:link rel="alternate" hreflang="ja" href="https://docs.python.org/ja/3.5/"/>
<xhtml:link rel="alternate" hreflang="ko" href="https://docs.python.org/ko/3.5/"/>
<xhtml:link rel="alternate" hreflang="pl" href="https://docs.python.org/pl/3.5/"/>
<xhtml:link rel="alternate" …
```
=> Start a sitemap.

build_docs.py
Per PEP 569 today's release of 3.8.10 is the last regular bugfix release.
=> Mark 3.8 as "security-fixes"

README.md, build_docs.py
=> Prepare docsbuild-scripts for the cpython migration to the main branch.

build_docs.py
If logs directory does not exist build will crash. So I added a command to create this folder if necessary.
=> logs_directory is now created if necessary

README.md, build_docs.py, build_docs_server.py, requirements.in, requirements.txt
=> Implement a simple github webook server to build the doc.

build_docs.py
CPython 3.10 docs have been repeatedly breaking, see https://github.com/python/cpython/issues/91483
It seems likely to me that this is related to https://github.com/python/cpython/pull/93159 (although the timeline doesn't match closely)
=> Shot in the dark fix for broken 3.10 render

build_docs.py
It appears that the venv keeps breaking: https://github.com/python/cpython/issues/91483
I'm not sure how to best help investigate, but adding some more logging seems like it could be useful :-)
=> Run pip freeze after installing requirements

build_docs.py
We have completed the translation of all the required files as specified in [PEP 545](https://peps.python.org/pep-0545/#add-translation-to-the-language-switcher).
Translation repo: https://github.com/python/python-docs-tr
=> Add Turkish to language switcher

build_docs.py
Changes aims to fix the problem on building Japanese PDF doc reported the following issue. 
https://github.com/python/python-docs-ja/issues/35
I've confirmed the the error disappeared in the build of Python 3.11 documentation on Docker container based on Ubuntu 22.04. 
Please note that this fix is a workaround to avoid confronting error rather than the one to fix essential problem. Given that the `U+C4CF` is Korean character, I added an option to use Korean latex package. It is weird that Korean latex package is required to build Japanese documentation. But it appears that it somehow works. 
Any suggestions are welcome. Thanks in advance!
=> Fix japanese doc build error

build_docs.py
Reverts python/docsbuild-scripts#144
It did not worked, see https://github.com/python/docsbuild-scripts/pull/144
=> Revert "Fix japanese doc build error"

build_docs.py
Fix Unicode character error building Japanese PDF documents.
See https://github.com/python/python-docs-ja/issues/31, https://github.com/python/python-docs-ja/issues/35
- Use LuaTex instead of pLatex.
- Use ltjsbook and ltjsarticle as document class.
- Temporarily replace U+FFFD with '?' until updated luatex is released (https://github.com/TeX-Live/luatex/commit/eaa95ce0a141eaf7a02).
=> Fix Unicode character error building Japanese PDF documents

build_docs.py
Provide set of allowed choices for branch CLI argument. Set metavar to most recent version.
Previously providing not supported branch name would effect with executing the script for empty list of versions (false negative). By providing choices we validate provided argument (disallowed value will exit the script with exit code `2`).
Example:
```
% python build_docs.py … --branch 3.121
usage: build_docs.py [-h] [-q] [-b 3.12] [-r BUILD_ROOT] [-w WWW_ROOT] [--skip-cache-invalidation] [--group GROUP] [--log-directory LOG_DIRECTORY] [--languages [fr ...]] [--version] [--theme THEME]
build_docs.py: error: argument -b/--branch: invalid choice: '3.121' (choose from 'origin/main', 'origin/3.11', 'origin/3.10', 'origin/3.9', 'origin/3.8', 'origin/3.7', '3.12', '3.11', '3.10', '3.9', '3.8', '3.7', …
```
=> Provide allowed choices for branch CLI argument

templates/switchers.js
Possibly fixes #159.
Is there a good way to test this?
=> Replace jQuery with vanilla JavaScript

build_docs.py
Fixes https://github.com/python/python-docs-theme/issues/134.
So we don't need someone to ssh in to the server and manually delete the venv.
=> 'pip install --upgrade' to automatically deploy newer requirements

templates/indexsidebar.html
Update to use the canonical form of https://peps.python.org/
Matches https://github.com/python/cpython/blob/main/Doc/tools/templates/indexsidebar.html, already updated in https://github.com/python/cpython/pull/32124.
=> Update PEP Index URL to canonical form

build_docs.py
Beware it's based on the unmerged `config` branch...
=> Do not rebuild when it's not needed (like there's no updates).

build_docs.py
Backup suffix following the -i option is required on macOS.
=> Provide a backup suffix for sed -i (in-place) option when on MacOS

build_docs.py, requirements.txt
This resolves the deprecation warning reported in #181.
=> Migrate sentry from 1.x to 2.x

build_docs.py
This PR mainly exists to run the rebuild loop on language-version pairs in definition order rather than reversed (so we run en/3.14 first rather than zh-tw/3.14), and I cleaned up a few other things too. Perhaps easiest to review by commit.
A
=> Improve ordering

.pre-commit-config.yaml, build_docs.py, check_times.py
This is the script I have been using locally, based on Hugo's original script. It probably makes sense to have one version or another in version control history?
Happy to change anything, really.
A
=> Add the check-times script

build_docs.py
Replaces various things with pathlib alternatives. Helps to reduce nesting.
A
=> Use pathlib more

build_docs.py
* Round duration seconds to the nearest integer
* Change `last_build` to the start time instead of the end time
* Don't include microseconds in ``last_build_start``
This allows using the useful data captured in `state.toml` for longitudinal analysis via the log files. It would simplify much of the code in ``check_times.py`` (should we include ``trigger`` in `state.toml`?)
A
=> Log updates to ``state.toml``

.gitignore, build_docs.py
Towards https://github.com/python/docs-community/issues/131
If either of the options to ``--select-output`` is given, a different lockfile is generated and checked. We also invert some options because in the future both HTML and non-HTML builds will require archiving their files, so we only skip archiving when ``--quick`` is passed.
If ``--select-output`` is missing, the current behaviour is retained, so merging this should have no impact on the current process.
I believe that running ``rsync -a --delete-delay --filter P archives/ <build path> <target path>`` is harmless on quick builds, so we remove an if/else here.
=> Add ``--select-output``

build_docs.py
The no-HTML build failed with an error that `switchers.js` doesn't exist. In general, it doesn't make sense to run these tasks on the non-HTML builds.
```pytb
Traceback (most recent call last):
File "/srv/docsbuild/scripts/build_docs.py", line 644, in run
self.build()
File "/srv/docsbuild/scripts/build_docs.py", line 770, in build
setup_switchers(
File "/srv/docsbuild/scripts/build_docs.py", line 405, in setup_switchers
switchers_path.write_text(rendered_template, encoding="UTF-8")
File "/usr/lib/python3.10/pathlib.py", line 1154, in write_text
with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
File "/usr/lib/python3.10/pathlib.py", line 1119, in open
return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such …
```
=> Only run HTML-specific tasks in builds that output HTML

build_docs.py
Currently the non-HTML and HTML-only builds are overwriting each other's state.
A
=> Set the ``state.toml`` filename based upon ``--select-output``

build_docs.py
Resolves https://github.com/python/docsbuild-scripts/pull/205#issuecomment-2385243164 cc @hugovk 
Currently, the non-HTML build for HTML-only languages runs the ``autobuild-dev-html`` target, because the `html_only` property checks `self.language.html_only`.
A
=> Skip non-HTML builds for HTML-only languages

build_docs.py
I wondered why https://docs.python.org/3.13/ still said "3.13.0rc2" -- the most recent commits pushed created `Misc/NEWS.d/3.13.0rc3.rst` from `Misc/NEWS.d/next/`, but had no changes to `Doc/`, so no rebuild has been triggered. This PR fixes this (edge case).
A
=> Rebuild on changes to Misc/NEWS.d/

build_docs.py
A proposal, as this would add to the logs, but would also let us see which steps are taking more time in sphinx.
Quiet mode was originally added in 8d82617d78e25448b379003a811629b7329209b1.
A
=> Run `sphinx-build` with the default verbosity level

build_docs.py
Per Ezio's comments https://github.com/python/docsbuild-scripts/pull/203#discussion_r1788973212
I also replaced `textwrap.indent` with a gencomp as I noticed that the same string was split, joined, split, and joined again, which seemed wasteful.
A
=> Harmonise run() and run_with_logging()

templates/robots.txt
Follows #165. Python 3.8 has ceased to be.
A
=> Add 3.8 to robots.txt

build_docs.py
`robots.txt` does not and has never used template variables. This removes the needless Jinja steps and simply copies the file.
A
=> Simplify copying robots.txt

build_docs.py
`self.name == ("3.8", "3.9")` is never true, as the test should be `in`. However it is also unneeded, as both versions have a requirements.txt file with identical versions:
* https://github.com/python/cpython/blob/3.8/Doc/requirements.txt
* https://github.com/python/cpython/blob/3.9/Doc/requirements.txt
A
=> Simplify `Version.requirements`

build_docs.py
Sadly I miscalculated in https://github.com/python/docsbuild-scripts/issues/209#issuecomment-2406092614, and the duration of the full rebuild loop is more along the lines of three hours. This introduces a `only-html-en` variant that we can use to have a more frequent English-only build job.
This is inspired by something @hugovk [mentioned](https://github.com/python/docs-community/issues/131#issuecomment-2389812605) a while ago.
A
=> Add an HTML-only (English) build variant

build_docs.py
The post-build tasks currently take around five minutes. I suspect it will be the canonical checking, but empirical data is better than mere suspicion.
A
=> Add logging in post-build tasks

build_docs.py
This follows on from https://github.com/python/psf-salt/issues/287, where we have added `Surrogate-Key` headers to all language-version pairs. These are consumed internally by Fastly and can be used to purge an entire set of pages at once, rather than doing so per-page.
I've tested using `curl` to send the requests manually and it seems to work -- we get a cache hit, purge the surrogate key, and then get a cache miss.
This should also marginally improve build times, but I think the simplification stands alone as a value proposition.
A
=> Purge using Surrogate-Key headers

build_docs.py
Currently, `/3/` is not purged when `/3.13/` updates (and the same for `/dev/`). This is a quick fix, a better solution would either to use rewrite rules in Nginx or to check if the symlink target has been rebuilt.
A
=> Always purge symlinks

templates/switchers.js
CPython's PR didn't apply here.
https://github.com/python/cpython/pull/125934
=> Add context labels to the version switcher

templates/switchers.js
* Modernise (remove obsolete polyfills, update to use e.g. arrow functions, use `Map` over object literals)
* Improve documentation (add JSDoc comments)
* Improve handling for local browsing (`file:` URIs)
* Improve core redirection logic
* Improve readability (prefer named functions to anonymous, give more variables names)
* Create switchers from DOM nodes rather than less-secure parsing of HTML strings
A
=> Refactor switchers.js

templates/switchers.js
On a non-local network, promises are sufficiently slow to resolve that the fall-through executes first. Switching to async-await should ensure strict ordering.
A
=> Convert promises to async-await

templates/switchers.js
It seems that [deep-cloning](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode) doesn't preserve all attributes (namely `selected = true`).
=> Always create new select nodes

build_docs.py, templates/switchers.js
JSON objects are technically unsorted, and we want to preserve order. Also, this avoids a call to `Object.entries()`
A
=> Create switchers maps from arrays of pairs

config.toml
I believe this is all that is necessary. If there is much more to be done I can close my PR and let someone who knows the config better do this.
=> Enable the Polish translation in the language switcher

templates/switchers.js
Closes https://github.com/python/docsbuild-scripts/issues/241
See 
https://docs.python.org/3.10/_static/documentation_options.js
```js
var DOCUMENTATION_OPTIONS = {
URL_ROOT: document.getElementById("documentation_options").getAttribute('data-url_root'),
VERSION: '3.10.16',
LANGUAGE: 'None',
COLLAPSE_INDEX: false,
BUILDER: 'html',
FILE_SUFFIX: '.html',
LINK_SUFFIX: '.html',
HAS_SOURCE: true,
SOURCELINK_SUFFIX: '.txt',
NAVIGATION_WITH_KEYS: false
};
```
vs 
https://docs.python.org/3.11/_static/documentation_options.js
```js
const DOCUMENTATION_OPTIONS = {
VERSION: '3.11.11',
LANGUAGE: 'en',
COLLAPSE_INDEX: false,
BUILDER: 'html',
FILE_SUFFIX: '.html',
LINK_SUFFIX: '.html',
HAS_SOURCE: true,
SOURCELINK_SUFFIX: '.txt',
NAVIGATION_WITH_KEYS: false,
SHOW_SEARCH_SUMMARY: true, …
```
=> Identify the language correctly for older versions

build_docs.py, config.toml
An alternative to #244 (closes #244, #238 if merged).
I think it is cleaner to use a new attribute for the local/translated/native name for each language, rather than overloading the `name` field. I agree with @encukou that the English name should come first, and that we should not de-emphasise the other name by using brackets for it.
cc @StanFromIreland @rffontenelle @m-aciek as I can't request you as reviewers.
A
=> Include languages' translated names in the switcher

build_docs.py
We now use Sphinx 8.2, which should properly convert command-line overrides to Boolean values.
=> Re-enable translation_progress_classes

.github/workflows/test.yml, build_docs.py, tox.ini
The docs server is now running Python 3.13: https://github.com/python/psf-salt/pull/551
We can stop testing 3.10-3.12, and let's add 3.14 as well.
=> Test Python 3.14 and remove 3.10-1.12

build_docs.py
The new symlink log messages would look nicer with surrounding slashes. From ``DEBUG: Creating symlink from 3 to 3.13`` to ``DEBUG: Creating symlink from /3/ to /3.13/``, etc.
=> Adjust symlink log message

build_docs.py
The `build_docs()` function uses the `build_succeeded` set to track which versions need updated symlinks. However, `DocBuilder.run()` currently always returns `True` unless an exception was raised. Here, we allow returning a third state (`None`) to signal skipped builds.
=> Account for skipped builds in ``build_docs()``

build_docs.py
Currently, ``proofread_canonicals()`` takes c. 4-5 minutes, with the vast majority of time spent reading the files from disk. This PR improves performance to c. 100-120 seconds by using multiple threads to check the files. We also switch to byte methods over `re` for another slight improvement, avoiding Unicode encoding/decoding.
A
=> Improve performance for ``proofread_canonicals()``

build_docs.py
In https://github.com/python/cpython/pull/132220, the form of the canonical tag was changed to remove the self-closing ` />`. To handle this we switch back to a regular expression with an optional group.
=> Account for recent removal of self-closing tags

.coveragerc, .github/workflows/test.yml, README.md, build_docs.py, tests/test_build_docs_version.py, tests/test_build_docs_versions.py, tox.ini
A full set of Python 3.9-3.13 security+bugfix releases were made last week:
https://discuss.python.org/t/python-3-13-1-3-12-8-3-11-11-3-10-16-and-3-9-21-are-now-available/73214
The bugfix branches (3.12 and 3.13) are automatically built on cron.
The security branches (3.9-3.11) need manual rebuilds. We also have the final 3.8 to manually run. It's taken 16 and 13 hours for a full build of the first two so far (3.11 and 3.10; see https://github.com/python/docsbuild-scripts/issues/216).
We will certainly have big omnibus security releases in the future and instead of having to run each one separately:
```sh
/srv/docsbuild/venv/bin/python /srv/docsbuild/scripts/build_docs.py --branch 3.11
/srv/docsbuild/venv/bin/python /srv/docsbuild/scripts/build_docs.py --branch 3.10 …
```
=> Allow passing multiple branches to build via CLI

build_docs.py, requirements.txt
ref #266
This will allow us to write these files out to disk from python/psf-salt, and ensure they're picked up whenever/however build_docs.py is executed.
=> move environment vars to a configuration file

build_docs.py
Python 3.8 & 3.9 use Sphinx 2.4.4, and Python 3.10 uses Sphinx 3.4.3. These require the `imghdr` module, which was removed in Python 3.13. The venvs now use Python 3.13, so we need to restore the `imghdr` module for those versions.
=> Require imghdr for building Python 3.8-3.10

README.md, build_docs.py
This can be useful e.g. when the a new version of the theme is released, or DBS configuration has changed.
Question: Perhaps `--force` instead of `--force-build`?
A
=> Add ``--force-build`` to always rebuild

build_docs.py
By default, macOS comes with an old FreeBSD version of sed which doesn't have as many options as GNU sed you find elsewhere.
Default:
```console
❯ which sed
/usr/bin/sed
```
```console
❯ sed --version
sed: illegal option -- -
usage: sed script [-EHalnru] [-i extension] [file ...]
sed [-EHalnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```
```console
❯ man sed
[snip]
macOS 15.3                                    June 10, 2020                                   macOS 15.3
```
Instead, I use GNU sed installed via Homebrew:
```console
❯ brew install gsed
==> Downloading https://formulae.brew.sh/api/formula.jws.json
==> Downloading https://formulae.brew.sh/api/cask.jws.json
==> Downloading https://ghcr.io/v2/homebrew/core/gnu-sed/manifests/4.9-3
Already downloaded: …
```
=> Check if we're using GNU sed instead of macOS

build_docs.py
For Python 3.12+, we've changed `Doc/Makefile` to add the `dist-html` target. For older versions and the HTML only target, `dist` isn't created, so some commands fail. This ensures that the directory exists.
```
ERROR en/3.11: Run: 'chown -R :docs /srv/docsbuild/cpython-only-html-en/Doc/dist' KO:
chown: cannot access '/srv/docsbuild/cpython-only-html-en/Doc/dist': No such file or directory
```
A
=> Ensure that `Doc/dist` exists

build_docs.py
As noted in the comment, this was fixed [1] and released in LuaTex 1.16.
\[1]: https://gitlab.lisn.upsaclay.fr/texlive/luatex/-/commit/af5faf1af25dc00f02356eb0e99bfe26b8de2f61
We have LuaTex 1.17 on the server:
```
adam@docs:/srv/docsbuild/scripts$ luatex -credits
This is LuaTeX, Version 1.17.0 (TeX Live 2023/Debian)
[...]
Development id: 7581
```
=> Remove use of the `sed` command

build_docs.py
#271 led to a new error, `cp: missing destination file operand after '/srv/docs.python.org/3.9/archives'`.
=> Only copy archive files if the dist directory exists

.github/workflows/test.yml
After removing sed in https://github.com/python/docsbuild-scripts/pull/272, we should now support Windows in addition to Linux and macOS?
Let's test them to avoid regressions.
=> Run unit tests on three operating systems

build_docs.py, templates/_docs_by_version.html, templates/indexsidebar.html
Remove the double-rendering of `indexsidebar.html`. For end-of-life versions, change the sidebar to contain a link to the current stable version. For non-EOL versions, overwrite the new `_docs_by_version.html` file with the list of links.
This also means that we can now remove `versions` as an argument to `DocBuilder`.
A
=> Simplify generation of `indexsidebar.html`

build_docs.py
Towards using fewer Unix-only utilities.
A
=> Create a function to perform ``chgrp`` operations

build_docs.py
Towards using fewer Unix-only utilities.
A
=> Create a function for ``chmod`` operations

.github/workflows/test.yml, build_docs.py
Towards using fewer Unix-only utilities.
A
=> Remove subprocess calls for copying archive files

build_docs.py
Rebuilding 3.5, 3.6, and 3.7 fail with the following error. Try constraining them to a previous version of blurb.
```pytb
Traceback (most recent call last):
File "/srv/docsbuild/venv-3.7/bin/blurb", line 8, in <module>
sys.exit(main())
~~~~^^
File "/srv/docsbuild/venv-3.7/lib/python3.13/site-packages/blurb/blurb.py", line 1203, in main
sys.exit(fn(*filtered_args, **kwargs))
~~^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/docsbuild/venv-3.7/lib/python3.13/site-packages/blurb/blurb.py", line 982, in merge
write_news(output, versions=versions)
~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/docsbuild/venv-3.7/lib/python3.13/site-packages/blurb/blurb.py", line 1014, in write_news
blurbs.load(filenames[0])
~~~~~~~~~~~^^^^^^^^^^^^^^
File "/srv/docsbuild/venv-3.7/lib/python3.13/site-packages/blurb/blurb …
```
=> Constrain blurb to version 1.1 or older

build_docs.py
=> Add constraints for sphinxcontrib dependencies

build_docs.py
These options are new in Python 3.14.
Docs:
* https://docs.python.org/3.14/library/argparse.html#suggest-on-error
* https://docs.python.org/3.14/library/argparse.html#color
=> Enable ``suggest_on_error`` for argparse

build_docs.py
In the inner loop, we operate on version-language pairs. These are currently only joined in the type system via tuples, or not at all. By introducing the `BuildMetadata` class, we make the link explicit.
My intent is to (later) add further attributes to `BuildMetadata` (e.g. the directory paths), making `BuildMetadata` a data-only class that performs no actions, with `DocBuilder` performing the actual build. For example, `DocBuilder.html_only` could be fully merged into `BuildMetadata`. 
A
=> Add the ``BuildMetadata`` class

check_times.py
By default, this scripts outputs the build times for all three types of builds. This can be long, for example 1,582 lines.
Sometimes I only want to check one block, for example, non-HTML builds in https://github.com/python/docsbuild-scripts/issues/306.
This PR allows you to select which type of build. By default, it shows all three.
=> Add options to only show certain build times

config.toml
I prepared the translation for the translation switcher. The repository contains a Romanian translation of: [ bugs.po, tutorial/*.po, library/functions.po ]. It also includes some necessary partial translations to make the Romanian version of the tutorial easier to use: [ glossary.po (only the index), sphinx.po (the fragments used for the splash-page and for the download page) ]. I have tested the translation against the latest docs from the [Python/cpython, branch 3.13](https://github.com/python/cpython/tree/3.13).
=> Add Romanian translation to the language switcher
